import { AIVideoProviderConfig, VideoPreset } from '../../types/videoProvider';

export const DEFAULT_VIDEO_PROVIDER_CONFIGS: AIVideoProviderConfig[] = [
  {
    providerId: 'seedance-2-0-fast-pro',
    modelId: 'seedance-2.0-fast',
    displayName: 'Seedance 2.0 Fast Pro',
    label: 'Fast Generation • Cinematic Motion',
    description: 'Generasi video ultra cepat dengan pergerakan kamera sinematik dan konsistensi subjek tinggi.',
    badgeType: 'seedance-2-fast',
    apiEndpoint: 'https://api.seedance.ai/v2/video/generations',
    apiKeyEnvVar: 'SEEDANCE_API_KEY',
    isConnected: false,
    isEnabled: true,
    isDefault: true,
    order: 1,
    specialties: ['Fast Video', 'Cinematic Motion', 'Subject Consistency'],
    recommendedCategory: 'fast',
    fallbackProviderId: 'veo-3-1-fast-pro',
    capabilities: {
      supportsImageToVideo: true,
      supportsTextToVideo: true,
      supportsNegativePrompt: true,
      supportsCameraControl: true,
      supportsDuration: true,
      supportedDurations: ['3s', '5s', '8s'],
      supportsAspectRatio: true,
      supportedAspectRatios: ['16:9', '9:16', '1:1'],
      supportsFPS: true,
      supportedFPS: [24, 30],
      supportsReferenceImage: true,
      supportsAudio: false,
      supportsSeed: true,
      supportsResolution: true,
      supportedResolutions: ['720p', '1080p'],
      maxDurationSec: 8
    }
  },
  {
    providerId: 'veo-3-1-fast-pro',
    modelId: 'veo-3.1-fast',
    displayName: 'Veo 3.1 Fast Pro',
    label: 'Fast • High Quality • Cinematic',
    description: 'Generasi cepat dengan kualitas sinematik tinggi, dynamic camera motion, dan temporal stability.',
    badgeType: 'veo-fast',
    apiEndpoint: 'https://api.koboillm.com/v1/videos/generations',
    apiKeyEnvVar: 'VEO_API_KEY',
    isConnected: false,
    isEnabled: true,
    order: 2,
    specialties: ['Fast High Quality', 'Cinematic Pan/Tilt', 'Audio Integration'],
    recommendedCategory: 'fast',
    fallbackProviderId: 'veo-3-1-lite-pro',
    capabilities: {
      supportsImageToVideo: true,
      supportsTextToVideo: true,
      supportsNegativePrompt: true,
      supportsCameraControl: true,
      supportsDuration: true,
      supportedDurations: ['3s', '5s', '8s', '10s'],
      supportsAspectRatio: true,
      supportedAspectRatios: ['16:9', '9:16', '1:1', '4:5'],
      supportsFPS: true,
      supportedFPS: [24, 30, 60],
      supportsReferenceImage: true,
      supportsAudio: true,
      supportsSeed: true,
      supportsResolution: true,
      supportedResolutions: ['720p', '1080p', '4k'],
      maxDurationSec: 10
    }
  },
  {
    providerId: 'veo-3-1-lite-pro',
    modelId: 'veo-3.1-lite',
    displayName: 'Veo 3.1 Lite Pro',
    label: 'Lightweight • Fast Generation',
    description: 'Model ringan dan efisien untuk rendering cepat, draft pratinjau, dan konten media sosial ringkas.',
    badgeType: 'veo-lite',
    apiEndpoint: 'https://api.koboillm.com/v1/videos/generations',
    apiKeyEnvVar: 'VEO_API_KEY',
    isConnected: false,
    isEnabled: true,
    order: 3,
    specialties: ['Quick Preview', 'Low Latency', 'Social Media'],
    recommendedCategory: 'lightweight',
    fallbackProviderId: 'veo-3-0-fast-pro',
    capabilities: {
      supportsImageToVideo: true,
      supportsTextToVideo: true,
      supportsNegativePrompt: false,
      supportsCameraControl: true,
      supportsDuration: true,
      supportedDurations: ['3s', '5s'],
      supportsAspectRatio: true,
      supportedAspectRatios: ['16:9', '9:16', '1:1'],
      supportsFPS: true,
      supportedFPS: [24, 30],
      supportsReferenceImage: false,
      supportsAudio: false,
      supportsSeed: true,
      supportsResolution: true,
      supportedResolutions: ['720p', '1080p'],
      maxDurationSec: 5
    }
  },
  {
    providerId: 'veo-3-1-pro',
    modelId: 'veo-3.1',
    displayName: 'Veo 3.1 Pro',
    label: 'Premium Quality • Advanced Video',
    description: 'Standar kualitas premium teratas dengan resolusi maksimal, fidelity temporal, dan audio ambient sinematik.',
    badgeType: 'veo-pro',
    apiEndpoint: 'https://api.koboillm.com/v1/videos/generations',
    apiKeyEnvVar: 'VEO_API_KEY',
    isConnected: false,
    isEnabled: true,
    order: 4,
    specialties: ['Premium Cinematic', 'Advanced Video', 'Photorealistic Lighting'],
    recommendedCategory: 'cinematic',
    fallbackProviderId: 'veo-3-1-fast-pro',
    capabilities: {
      supportsImageToVideo: true,
      supportsTextToVideo: true,
      supportsNegativePrompt: true,
      supportsCameraControl: true,
      supportsDuration: true,
      supportedDurations: ['4s', '5s', '8s', '10s'],
      supportsAspectRatio: true,
      supportedAspectRatios: ['16:9', '9:16', '1:1', '4:5'],
      supportsFPS: true,
      supportedFPS: [24, 25, 30, 60],
      supportsReferenceImage: true,
      supportsAudio: true,
      supportsSeed: true,
      supportsResolution: true,
      supportedResolutions: ['1080p', '4k'],
      maxDurationSec: 10
    }
  },
  {
    providerId: 'veo-3-0-fast-pro',
    modelId: 'veo-3.0-fast',
    displayName: 'Veo 3.0 Fast Pro',
    label: 'Fast Generation • High Quality',
    description: 'Generasi cepat dengan kestabilan visual tinggi dan warna yang kontras.',
    badgeType: 'veo-3-green',
    apiEndpoint: 'https://api.koboillm.com/v1/videos/generations',
    apiKeyEnvVar: 'VEO_API_KEY',
    isConnected: false,
    isEnabled: true,
    order: 5,
    specialties: ['High-Quality Fast', 'Stable Camera', 'Vibrant Visuals'],
    recommendedCategory: 'high_quality',
    fallbackProviderId: 'seedance-2-0-fast-pro',
    capabilities: {
      supportsImageToVideo: true,
      supportsTextToVideo: true,
      supportsNegativePrompt: false,
      supportsCameraControl: true,
      supportsDuration: true,
      supportedDurations: ['3s', '5s', '8s'],
      supportsAspectRatio: true,
      supportedAspectRatios: ['16:9', '9:16', '1:1'],
      supportsFPS: true,
      supportedFPS: [24, 30],
      supportsReferenceImage: true,
      supportsAudio: true,
      supportsSeed: true,
      supportsResolution: true,
      supportedResolutions: ['720p', '1080p'],
      maxDurationSec: 8
    }
  },
  {
    providerId: 'google-omni-1-1',
    modelId: 'google-omni-1.1-video',
    displayName: 'Google Omni 1.1',
    label: 'Advanced AI Video • Creative Motion',
    description: 'Model video multimodal cerdas dengan pemahaman fisika mendalam dan gerakan kreatif alami.',
    badgeType: 'omni',
    apiEndpoint: 'https://api.omni.google/v1/video',
    apiKeyEnvVar: 'GOOGLE_OMNI_API_KEY',
    isConnected: false,
    isEnabled: true,
    order: 6,
    specialties: ['Creative AI Video', 'Complex Motion', 'Physically Grounded'],
    recommendedCategory: 'creative',
    fallbackProviderId: 'seedance-2-0-fast-pro',
    capabilities: {
      supportsImageToVideo: true,
      supportsTextToVideo: true,
      supportsNegativePrompt: true,
      supportsCameraControl: true,
      supportsDuration: true,
      supportedDurations: ['3s', '5s', '6s', '10s'],
      supportsAspectRatio: true,
      supportedAspectRatios: ['16:9', '9:16', '1:1'],
      supportsFPS: true,
      supportedFPS: [24, 30],
      supportsReferenceImage: true,
      supportsAudio: false,
      supportsSeed: true,
      supportsResolution: true,
      supportedResolutions: ['720p', '1080p'],
      maxDurationSec: 10
    }
  },
  {
    providerId: 'happy-horse-1-0',
    modelId: 'happy-horse-1.0',
    displayName: 'Happy Horse 1.0',
    label: 'Creative Motion • Image-to-Video',
    description: 'Spesialis animasi dinamis, pergerakan artistik, dan ekspresi visual yang imajinatif.',
    badgeType: 'horse',
    apiEndpoint: 'https://api.happyhorse.ai/v1/animate',
    apiKeyEnvVar: 'HAPPY_HORSE_API_KEY',
    isConnected: false,
    isEnabled: true,
    order: 7,
    specialties: ['Creative Motion', 'Expressive Animation', 'Anime / Stylized'],
    recommendedCategory: 'creative',
    fallbackProviderId: 'seedance-2-0-fast-pro',
    capabilities: {
      supportsImageToVideo: true,
      supportsTextToVideo: false,
      supportsNegativePrompt: true,
      supportsCameraControl: true,
      supportsDuration: true,
      supportedDurations: ['3s', '5s', '8s'],
      supportsAspectRatio: true,
      supportedAspectRatios: ['16:9', '9:16', '1:1', '4:5'],
      supportsFPS: true,
      supportedFPS: [24, 25, 30],
      supportsReferenceImage: true,
      supportsAudio: false,
      supportsSeed: true,
      supportsResolution: true,
      supportedResolutions: ['720p', '1080p'],
      maxDurationSec: 8
    }
  }
];

export const VIDEO_GENERATION_PRESETS: VideoPreset[] = [
  {
    id: 'cinematic',
    name: 'Cinematic',
    desc: 'Pencahayaan dramatis dan gerak kamera push-in sinematik.',
    motionPromptSuffix: 'Cinematic slow push-in, shallow depth of field, gentle atmospheric movement, photorealistic 8k lighting, subtle anamorphic lens flare.',
    defaultCameraMotion: 'Cinematic Push-In',
    defaultIntensity: 'Medium',
    iconName: 'Film'
  },
  {
    id: 'commercial',
    name: 'Product Commercial',
    desc: 'Sorotan produk berputar halus dengan pencahayaan studio bersih.',
    motionPromptSuffix: 'Smooth commercial showcase, gentle orbital rotation around product, luxury studio lighting, crisp reflections, high temporal stability.',
    defaultCameraMotion: 'Orbit',
    defaultIntensity: 'Low',
    iconName: 'ShoppingBag'
  },
  {
    id: 'portrait',
    name: 'Portrait Motion',
    desc: 'Kedipan alami, hembusan rambut halus, dan pernapasan riil.',
    motionPromptSuffix: 'Subtle natural facial expressions, gentle blinking, micro eye movements, soft hair movement in breeze, lifelike breathing rhythm.',
    defaultCameraMotion: 'Slow Zoom In',
    defaultIntensity: 'Low',
    iconName: 'User'
  },
  {
    id: 'nature',
    name: 'Nature & Landscape',
    desc: 'Pohon bergoyang, aliran air, dan awan bergerak perlahan.',
    motionPromptSuffix: 'Gentle wind blowing through foliage, tranquil water ripples, slow moving clouds, atmospheric mist, realistic natural physics.',
    defaultCameraMotion: 'Pan Right',
    defaultIntensity: 'Medium',
    iconName: 'Trees'
  },
  {
    id: 'travel',
    name: 'Travel & Scenery',
    desc: 'Pergerakan drone melayang menyusuri panorama luas.',
    motionPromptSuffix: 'Sweeping scenic drone flyover, expansive majestic vista, golden hour sunlight, smooth glide over landscape, rich cinematic scale.',
    defaultCameraMotion: 'Tracking Shot',
    defaultIntensity: 'Medium',
    iconName: 'Compass'
  },
  {
    id: 'islamic',
    name: 'Islamic Visual',
    desc: 'Lentera lembut bercahaya, ornamen kaligrafi dengan nuansa damai.',
    motionPromptSuffix: 'Soft ambient warm lantern glow, peaceful serene atmosphere, gentle atmospheric dust particles floating, respectful reverent composition.',
    defaultCameraMotion: 'Slow Zoom In',
    defaultIntensity: 'Low',
    iconName: 'Moon'
  },
  {
    id: 'food',
    name: 'Food Advertisement',
    desc: 'Uap panas mengepul, lelehan saus, dan kelezatan hidangan.',
    motionPromptSuffix: 'Appetizing steam slowly rising, delicious glossy sauce dripping, slow tilt down highlighting textures, mouth-watering commercial grade.',
    defaultCameraMotion: 'Tilt Down',
    defaultIntensity: 'Low',
    iconName: 'Utensils'
  },
  {
    id: 'fashion',
    name: 'Fashion & Runway',
    desc: 'Kain melayang anggun, gerakan dinamis catwalk profesional.',
    motionPromptSuffix: 'Fluid dynamic fabric draping and motion, confident runway stride, editorial spotlight illumination, high-fashion styling.',
    defaultCameraMotion: 'Dolly In',
    defaultIntensity: 'High',
    iconName: 'Sparkles'
  },
  {
    id: 'architecture',
    name: 'Architecture',
    desc: 'Gerak kamera linear menyusuri interior dan sudut bangunan.',
    motionPromptSuffix: 'Architectural camera tracking along structure, realistic daylight transition across textures, clean geometric lines, professional interior showcase.',
    defaultCameraMotion: 'Dolly Out',
    defaultIntensity: 'Low',
    iconName: 'Building'
  },
  {
    id: 'social',
    name: 'Social Media Reel',
    desc: 'Tempo energetik yang memikat perhatian penonton dalam 3 detik.',
    motionPromptSuffix: 'Engaging dynamic action, vibrant high-contrast colors, snappy fluid movement, optimized for vertical short-form engagement.',
    defaultCameraMotion: 'Cinematic Push-In',
    defaultIntensity: 'High',
    iconName: 'Flame'
  },
  {
    id: 'anime',
    name: 'Anime / Creative',
    desc: 'Efek partikel magis dan visual anime bersemangat.',
    motionPromptSuffix: 'Dynamic anime aesthetic motion, glowing magical particle effects, dramatic stylized camera whip, expressive cel-shaded fluidity.',
    defaultCameraMotion: 'Orbit',
    defaultIntensity: 'Very High',
    iconName: 'Palette'
  },
  {
    id: 'slow-mo',
    name: 'Slow Motion',
    desc: 'Keanggunan gerak lambat 60fps dengan perincian ultra tajam.',
    motionPromptSuffix: 'Ultra high frame rate slow-motion, liquid droplet suspension, micro-motion clarity, mesmerizing cinematic cadence.',
    defaultCameraMotion: 'Static',
    defaultIntensity: 'Very Low',
    iconName: 'Clock'
  }
];
